
box = precise64
box_url = http://files.vagrantup.com/precise64.box

init:
	vagrant init ${box} ${box_url}

init-url:
	vagrant init ${box} ${box_url}

up:
	vagrant up

ssh:
	vagrant ssh

suspend:
	vagrant suspend

halt:
	vagrant halt

destory:
	vagrant destroy

reload:
	vagrant reload

status:
	vagrant status

global-status:
	vagrant gabal-status

add-box:
	vagrant box add ${box}

remove-box:
	vagrant box remove ${box}
