
vagrant-up-multi-provision:
	vagrant up

vagrant-up-chef-provision:
	vagrant up --provision-with=chef

vagrant-up-no-provision:
	vagrant up --no-provision

post-multi-provision:
	vagrant provision

puppet-post-provision:
	vagrant provision --provision-with=puppet

